#undef HAS_FFTW

#include <iomanip>
#include <iostream>
#include <vector>

#include "pdx/index.hpp"
#include "test_utils.hpp"

int main() {
    std::vector<std::string> index_types = {"pdx_f32", "pdx_u8"};
    // TODO: add "pdx_tree_f32", "pdx_tree_u8" once tree index crash is fixed
    std::vector<size_t> dimensions = {384};
    std::vector<size_t> nprobes = {1, 2, 4, 8, 16, 32, 64};

    std::cout << std::fixed << std::setprecision(4);
    std::cout << "// Ground truth recall@" << TestUtils::KNN << " values for test_search.cpp\n";
    std::cout << "// Generated by generate_test_ground_truth.out\n";
    std::cout << "// Copy-paste into RECALL_GROUND_TRUTH map:\n\n";

    for (size_t d : dimensions) {
        std::cerr << "Loading test data (d=" << d << ")...\n";
        auto data = TestUtils::LoadTestData(d);
        auto gt = TestUtils::ComputeBruteForceKNN(
            data.train.data(),
            data.queries.data(),
            TestUtils::N_TRAIN,
            TestUtils::N_QUERIES,
            d,
            TestUtils::KNN
        );

        for (const auto& index_type : index_types) {
            std::cerr << "  Building " << index_type << " (d=" << d << ")...\n";
            auto index =
                TestUtils::BuildIndex(index_type, data.train.data(), TestUtils::N_TRAIN, d);
            uint32_t num_clusters = index->GetNumClusters();
            std::cerr << "  Clusters: " << num_clusters << "\n";

            std::cout << "    // " << index_type << ", d=" << d << ", clusters=" << num_clusters
                      << "\n";

            auto all_nprobes = nprobes;
            all_nprobes.push_back(num_clusters);
            for (size_t nprobe : all_nprobes) {
                if (nprobe > num_clusters)
                    continue;
                index->SetNProbe(nprobe);
                float recall = TestUtils::ComputeAverageRecall(
                    *index, data.queries.data(), TestUtils::N_QUERIES, d, TestUtils::KNN, gt
                );
                std::cout << "    {{\"" << index_type << "\", " << d << ", " << nprobe << "}, "
                          << recall << "f},\n";
            }
        }
    }

    std::cerr << "Done.\n";
    return 0;
}
