#undef HAS_FFTW

#include <algorithm>
#include <cmath>
#include <gtest/gtest.h>
#include <map>
#include <string>
#include <tuple>
#include <unordered_set>
#include <vector>

#include "pdx/index.hpp"
#include "superkmeans/pdx/utils.h"
#include "test_utils.hpp"

namespace {

// Generated by generate_test_ground_truth.out — DO NOT EDIT MANUALLY
// clang-format off
const std::map<std::tuple<std::string, size_t, size_t>, float> RECALL_GROUND_TRUTH = {
    // pdx_f32, d=384, clusters=142
    {{"pdx_f32", 384, 1}, 0.4086f},
    {{"pdx_f32", 384, 2}, 0.4556f},
    {{"pdx_f32", 384, 4}, 0.5040f},
    {{"pdx_f32", 384, 8}, 0.5672f},
    {{"pdx_f32", 384, 16}, 0.6434f},
    {{"pdx_f32", 384, 32}, 0.7514f},
    {{"pdx_f32", 384, 64}, 0.8894f},
    {{"pdx_f32", 384, 142}, 0.9968f},
    // pdx_u8, d=384, clusters=142
    {{"pdx_u8", 384, 1}, 0.4072f},
    {{"pdx_u8", 384, 2}, 0.4542f},
    {{"pdx_u8", 384, 4}, 0.5026f},
    {{"pdx_u8", 384, 8}, 0.5656f},
    {{"pdx_u8", 384, 16}, 0.6416f},
    {{"pdx_u8", 384, 32}, 0.7484f},
    {{"pdx_u8", 384, 64}, 0.8830f},
    {{"pdx_u8", 384, 142}, 0.9780f},
};
// clang-format on

static constexpr size_t D = 384;
static constexpr float RECALL_TOLERANCE = 0.02f;
static constexpr float QUANTIZATION_RECALL_TOLERANCE = 0.05f;

class SearchTest : public ::testing::TestWithParam<std::string> {
  protected:
    void SetUp() override {}
};

TEST_P(SearchTest, RecallMatchesGroundTruth) {
    std::string index_type = GetParam();
    size_t d = D;
    auto data = TestUtils::LoadTestData(d);
    auto gt = TestUtils::ComputeBruteForceKNN(
        data.train.data(),
        data.queries.data(),
        TestUtils::N_TRAIN,
        TestUtils::N_QUERIES,
        d,
        TestUtils::KNN
    );

    auto index = TestUtils::BuildIndex(index_type, data.train.data(), TestUtils::N_TRAIN, d);
    ASSERT_NE(index, nullptr);
    index->SetNProbe(16);

    float recall = TestUtils::ComputeAverageRecall(
        *index, data.queries.data(), TestUtils::N_QUERIES, d, TestUtils::KNN, gt
    );

    auto key = std::make_tuple(index_type, d, size_t{16});
    auto it = RECALL_GROUND_TRUTH.find(key);
    if (it != RECALL_GROUND_TRUTH.end()) {
        float expected = it->second;
        EXPECT_NEAR(recall, expected, RECALL_TOLERANCE)
            << "Recall regression: got " << recall << ", expected ~" << expected;
    }
}

TEST_P(SearchTest, RecallMonotonicallyIncreasesWithNProbe) {
    std::string index_type = GetParam();
    size_t d = D;
    auto data = TestUtils::LoadTestData(d);
    auto gt = TestUtils::ComputeBruteForceKNN(
        data.train.data(),
        data.queries.data(),
        TestUtils::N_TRAIN,
        TestUtils::N_QUERIES,
        d,
        TestUtils::KNN
    );

    auto index = TestUtils::BuildIndex(index_type, data.train.data(), TestUtils::N_TRAIN, d);
    ASSERT_NE(index, nullptr);

    uint32_t num_clusters = index->GetNumClusters();
    std::vector<size_t> nprobes = {1, 2, 4, 8, 16, 32, 64};
    nprobes.push_back(num_clusters);
    nprobes.erase(
        std::remove_if(
            nprobes.begin(), nprobes.end(), [num_clusters](size_t p) { return p > num_clusters; }
        ),
        nprobes.end()
    );
    std::sort(nprobes.begin(), nprobes.end());
    nprobes.erase(std::unique(nprobes.begin(), nprobes.end()), nprobes.end());

    float prev_recall = 0.0f;
    for (size_t nprobe : nprobes) {
        index->SetNProbe(nprobe);
        float recall = TestUtils::ComputeAverageRecall(
            *index, data.queries.data(), TestUtils::N_QUERIES, d, TestUtils::KNN, gt
        );

        EXPECT_GE(recall, prev_recall - 0.01f) << "Recall decreased from " << prev_recall << " to "
                                               << recall << " when increasing nprobe to " << nprobe;
        prev_recall = recall;
    }
}

TEST_P(SearchTest, ResultsAreSortedByDistance) {
    std::string index_type = GetParam();
    size_t d = D;
    auto data = TestUtils::LoadTestData(d);
    auto index = TestUtils::BuildIndex(index_type, data.train.data(), TestUtils::N_TRAIN, d);
    index->SetNProbe(16);

    for (size_t q = 0; q < std::min<size_t>(50, TestUtils::N_QUERIES); ++q) {
        auto results = index->Search(data.queries.data() + q * d, TestUtils::KNN);
        for (size_t i = 1; i < results.size(); ++i) {
            EXPECT_LE(results[i - 1].distance, results[i].distance + 1e-6f)
                << "Results not sorted for query " << q << " at position " << i;
        }
    }
}

TEST_P(SearchTest, ResultIdsAreUnique) {
    std::string index_type = GetParam();
    size_t d = D;
    auto data = TestUtils::LoadTestData(d);
    auto index = TestUtils::BuildIndex(index_type, data.train.data(), TestUtils::N_TRAIN, d);
    index->SetNProbe(16);

    for (size_t q = 0; q < std::min<size_t>(50, TestUtils::N_QUERIES); ++q) {
        auto results = index->Search(data.queries.data() + q * d, TestUtils::KNN);
        std::unordered_set<uint32_t> seen;
        for (const auto& r : results) {
            EXPECT_TRUE(seen.insert(r.index).second)
                << "Duplicate ID " << r.index << " in query " << q;
        }
    }
}

TEST_P(SearchTest, ExhaustiveSearchMatchesGroundTruth) {
    std::string index_type = GetParam();
    size_t d = D;
    auto data = TestUtils::LoadTestData(d);
    auto gt = TestUtils::ComputeBruteForceKNN(
        data.train.data(),
        data.queries.data(),
        TestUtils::N_TRAIN,
        TestUtils::N_QUERIES,
        d,
        TestUtils::KNN
    );

    auto index = TestUtils::BuildIndex(index_type, data.train.data(), TestUtils::N_TRAIN, d);
    uint32_t num_clusters = index->GetNumClusters();
    index->SetNProbe(num_clusters);
    float recall = TestUtils::ComputeAverageRecall(
        *index, data.queries.data(), TestUtils::N_QUERIES, d, TestUtils::KNN, gt
    );

    auto key = std::make_tuple(index_type, d, static_cast<size_t>(num_clusters));
    auto it = RECALL_GROUND_TRUTH.find(key);
    if (it != RECALL_GROUND_TRUTH.end()) {
        EXPECT_NEAR(recall, it->second, RECALL_TOLERANCE)
            << "Exhaustive recall regression: got " << recall << ", expected ~" << it->second;
    }
}

// Quantization: U8 recall should be within 5% of F32
TEST(QuantizationTest, U8RecallWithinBound) {
    auto data = TestUtils::LoadTestData(D);
    auto gt = TestUtils::ComputeBruteForceKNN(
        data.train.data(),
        data.queries.data(),
        TestUtils::N_TRAIN,
        TestUtils::N_QUERIES,
        D,
        TestUtils::KNN
    );

    auto f32_index = TestUtils::BuildIndex("pdx_f32", data.train.data(), TestUtils::N_TRAIN, D);
    auto u8_index = TestUtils::BuildIndex("pdx_u8", data.train.data(), TestUtils::N_TRAIN, D);
    f32_index->SetNProbe(16);
    u8_index->SetNProbe(16);

    float f32_recall = TestUtils::ComputeAverageRecall(
        *f32_index, data.queries.data(), TestUtils::N_QUERIES, D, TestUtils::KNN, gt
    );
    float u8_recall = TestUtils::ComputeAverageRecall(
        *u8_index, data.queries.data(), TestUtils::N_QUERIES, D, TestUtils::KNN, gt
    );

    EXPECT_GE(u8_recall, f32_recall - QUANTIZATION_RECALL_TOLERANCE)
        << "U8 recall (" << u8_recall << ") too far below F32 recall (" << f32_recall << ")";
}

INSTANTIATE_TEST_SUITE_P(
    AllIndexTypes,
    SearchTest,
    ::testing::Values("pdx_f32", "pdx_u8", "pdx_tree_f32", "pdx_tree_u8"),
    [](const ::testing::TestParamInfo<std::string>& info) { return info.param; }
);

class UncommonDimTest : public ::testing::TestWithParam<size_t> {};

TEST_P(UncommonDimTest, RecallMonotonicAndExhaustiveNearPerfect) {
    size_t d = GetParam();
    constexpr size_t N_TRAIN = 2000;
    constexpr size_t N_QUERIES = 100;
    constexpr size_t KNN = 10;

    auto all_data = skmeans::MakeBlobs(N_TRAIN + N_QUERIES, d, 50, true, 5.0f, 2.0f, 42);
    const float* train = all_data.data();
    const float* queries = all_data.data() + N_TRAIN * d;

    auto gt = TestUtils::ComputeBruteForceKNN(train, queries, N_TRAIN, N_QUERIES, d, KNN);

    std::vector<std::string> types = {"pdx_f32"};
    if (d >= 10) {
        types.push_back("pdx_u8");
    }
    for (const auto& index_type : types) {
        SCOPED_TRACE(index_type);
        auto index = TestUtils::BuildIndex(index_type, train, N_TRAIN, d);
        ASSERT_NE(index, nullptr);

        std::vector<size_t> nprobes = {1, 8, 24, 32};
        uint32_t num_clusters = index->GetNumClusters();
        // Filter out nprobes that exceed num_clusters
        nprobes.erase(
            std::remove_if(
                nprobes.begin(),
                nprobes.end(),
                [num_clusters](size_t p) { return p > num_clusters; }
            ),
            nprobes.end()
        );
        nprobes.push_back(0); // 0 = all clusters

        float prev_recall = 0.0f;
        for (size_t nprobe : nprobes) {
            index->SetNProbe(nprobe);
            float total_recall = 0.0f;
            for (size_t q = 0; q < N_QUERIES; ++q) {
                auto results = index->Search(queries + q * d, KNN);
                total_recall += TestUtils::ComputeRecall(results, gt.indices[q], KNN);
            }
            float recall = total_recall / static_cast<float>(N_QUERIES);

            EXPECT_GE(recall, prev_recall - 0.01f)
                << "Recall decreased from " << prev_recall << " to " << recall
                << " at nprobe=" << nprobe << " d=" << d;
            prev_recall = recall;
        }

        // Exhaustive (nprobe=0) F32 should give near-perfect recall
        if (std::string(index_type) == "pdx_f32") {
            EXPECT_GE(prev_recall, 0.95f)
                << "Exhaustive F32 recall too low at d=" << d << ": " << prev_recall;
        }
    }
}

INSTANTIATE_TEST_SUITE_P(
    UncommonDimensionalities,
    UncommonDimTest,
    ::testing::Values(3, 5, 9, 13, 17, 63, 127, 200, 339, 500),
    [](const ::testing::TestParamInfo<size_t>& info) { return "d" + std::to_string(info.param); }
);

// --- Cosine Metric Tests ---

class CosineTest : public ::testing::TestWithParam<std::string> {};

TEST_P(CosineTest, CosineRecallMatchesL2OnNormalizedData) {
    std::string index_type = GetParam();
    constexpr size_t N = 2000;
    constexpr size_t NQ = 100;
    constexpr size_t K = 10;

    // Normalized data: COSINE and L2SQ should give identical rankings
    auto all_data = skmeans::MakeBlobs(N + NQ, D, 50, true, 5.0f, 2.0f, 42);
    const float* train = all_data.data();
    const float* queries = all_data.data() + N * D;

    PDX::PDXIndexConfig l2_config{
        .num_dimensions = static_cast<uint32_t>(D),
        .distance_metric = PDX::DistanceMetric::L2SQ,
        .seed = TestUtils::SEED,
        .normalize = true,
        .sampling_fraction = 1.0f,
        .hierarchical_indexing = true,
    };
    PDX::PDXIndexConfig cos_config{
        .num_dimensions = static_cast<uint32_t>(D),
        .distance_metric = PDX::DistanceMetric::COSINE,
        .seed = TestUtils::SEED,
        .sampling_fraction = 1.0f,
        .hierarchical_indexing = true,
    };

    auto l2_index = TestUtils::BuildIndexWithConfig(index_type, l2_config, train, N);
    auto cos_index = TestUtils::BuildIndexWithConfig(index_type, cos_config, train, N);
    ASSERT_NE(l2_index, nullptr);
    ASSERT_NE(cos_index, nullptr);

    l2_index->SetNProbe(0);
    cos_index->SetNProbe(0);

    for (size_t q = 0; q < NQ; ++q) {
        auto l2_results = l2_index->Search(queries + q * D, K);
        auto cos_results = cos_index->Search(queries + q * D, K);
        ASSERT_EQ(l2_results.size(), cos_results.size()) << "Size mismatch for query " << q;
        for (size_t i = 0; i < l2_results.size(); ++i) {
            EXPECT_EQ(l2_results[i].index, cos_results[i].index)
                << "ID mismatch at query " << q << " position " << i;
        }
    }
}

TEST_P(CosineTest, CosineRecallMonotonicity) {
    std::string index_type = GetParam();
    constexpr size_t N = 2000;
    constexpr size_t NQ = 100;
    constexpr size_t K = 10;

    // Non-normalized data: the index should auto-normalize for cosine
    auto all_data = skmeans::MakeBlobs(N + NQ, D, 50, false, 5.0f, 2.0f, 42);
    const float* train = all_data.data();
    const float* queries = all_data.data() + N * D;

    auto gt = TestUtils::ComputeBruteForceCosineKNN(train, queries, N, NQ, D, K);

    PDX::PDXIndexConfig config{
        .num_dimensions = static_cast<uint32_t>(D),
        .distance_metric = PDX::DistanceMetric::COSINE,
        .seed = TestUtils::SEED,
        .sampling_fraction = 1.0f,
        .hierarchical_indexing = true,
    };
    auto index = TestUtils::BuildIndexWithConfig(index_type, config, train, N);
    ASSERT_NE(index, nullptr);

    uint32_t num_clusters = index->GetNumClusters();
    std::vector<size_t> nprobes = {1, 8, 32};
    nprobes.push_back(num_clusters);
    nprobes.erase(
        std::remove_if(
            nprobes.begin(), nprobes.end(), [num_clusters](size_t p) { return p > num_clusters; }
        ),
        nprobes.end()
    );
    std::sort(nprobes.begin(), nprobes.end());
    nprobes.erase(std::unique(nprobes.begin(), nprobes.end()), nprobes.end());

    float prev_recall = 0.0f;
    for (size_t nprobe : nprobes) {
        index->SetNProbe(nprobe);
        float total_recall = 0.0f;
        for (size_t q = 0; q < NQ; ++q) {
            auto results = index->Search(queries + q * D, K);
            total_recall += TestUtils::ComputeRecall(results, gt.indices[q], K);
        }
        float recall = total_recall / static_cast<float>(NQ);
        EXPECT_GE(recall, prev_recall - 0.01f) << "Cosine recall decreased from " << prev_recall
                                               << " to " << recall << " at nprobe=" << nprobe;
        prev_recall = recall;
    }
}

TEST_P(CosineTest, CosineExhaustiveRecall) {
    std::string index_type = GetParam();
    constexpr size_t N = 2000;
    constexpr size_t NQ = 100;
    constexpr size_t K = 10;

    auto all_data = skmeans::MakeBlobs(N + NQ, D, 50, false, 5.0f, 2.0f, 42);
    const float* train = all_data.data();
    const float* queries = all_data.data() + N * D;

    auto gt = TestUtils::ComputeBruteForceCosineKNN(train, queries, N, NQ, D, K);

    PDX::PDXIndexConfig config{
        .num_dimensions = static_cast<uint32_t>(D),
        .distance_metric = PDX::DistanceMetric::COSINE,
        .seed = TestUtils::SEED,
        .sampling_fraction = 1.0f,
        .hierarchical_indexing = true,
    };
    auto index = TestUtils::BuildIndexWithConfig(index_type, config, train, N);
    ASSERT_NE(index, nullptr);
    index->SetNProbe(0);

    float total_recall = 0.0f;
    for (size_t q = 0; q < NQ; ++q) {
        auto results = index->Search(queries + q * D, K);
        total_recall += TestUtils::ComputeRecall(results, gt.indices[q], K);
    }
    float recall = total_recall / static_cast<float>(NQ);

    if (index_type == "pdx_f32") {
        EXPECT_GE(recall, 0.95f) << "Cosine F32 exhaustive recall too low: " << recall;
    } else {
        EXPECT_GE(recall, 0.90f) << "Cosine U8 exhaustive recall too low: " << recall;
    }
}

INSTANTIATE_TEST_SUITE_P(
    CosineMetric,
    CosineTest,
    ::testing::Values("pdx_f32", "pdx_u8"),
    [](const ::testing::TestParamInfo<std::string>& info) { return info.param; }
);

// --- Seed Determinism Tests ---

class SeedTest : public ::testing::TestWithParam<std::string> {};

TEST_P(SeedTest, SameSeedProducesSameResults) {
    std::string index_type = GetParam();
    auto data = TestUtils::LoadTestData(D);

    PDX::PDXIndexConfig config{
        .num_dimensions = static_cast<uint32_t>(D),
        .distance_metric = PDX::DistanceMetric::L2SQ,
        .seed = 42,
        .normalize = true,
        .sampling_fraction = 1.0f,
        .hierarchical_indexing = true,
    };

    auto index1 =
        TestUtils::BuildIndexWithConfig(index_type, config, data.train.data(), TestUtils::N_TRAIN);
    auto index2 =
        TestUtils::BuildIndexWithConfig(index_type, config, data.train.data(), TestUtils::N_TRAIN);
    index1->SetNProbe(16);
    index2->SetNProbe(16);

    for (size_t q = 0; q < 50; ++q) {
        auto r1 = index1->Search(data.queries.data() + q * D, TestUtils::KNN);
        auto r2 = index2->Search(data.queries.data() + q * D, TestUtils::KNN);
        ASSERT_EQ(r1.size(), r2.size()) << "Size mismatch for query " << q;
        for (size_t i = 0; i < r1.size(); ++i) {
            EXPECT_EQ(r1[i].index, r2[i].index)
                << "ID mismatch at query " << q << " position " << i;
            EXPECT_FLOAT_EQ(r1[i].distance, r2[i].distance)
                << "Distance mismatch at query " << q << " position " << i;
        }
    }
}

TEST_P(SeedTest, DifferentSeedProducesDifferentRotation) {
    std::string index_type = GetParam();
    auto data = TestUtils::LoadTestData(D);

    PDX::PDXIndexConfig config1{
        .num_dimensions = static_cast<uint32_t>(D),
        .distance_metric = PDX::DistanceMetric::L2SQ,
        .seed = 42,
        .normalize = true,
        .sampling_fraction = 1.0f,
        .hierarchical_indexing = true,
    };
    PDX::PDXIndexConfig config2{
        .num_dimensions = static_cast<uint32_t>(D),
        .distance_metric = PDX::DistanceMetric::L2SQ,
        .seed = 99,
        .normalize = true,
        .sampling_fraction = 1.0f,
        .hierarchical_indexing = true,
    };

    auto index1 =
        TestUtils::BuildIndexWithConfig(index_type, config1, data.train.data(), TestUtils::N_TRAIN);
    auto index2 =
        TestUtils::BuildIndexWithConfig(index_type, config2, data.train.data(), TestUtils::N_TRAIN);
    index1->SetNProbe(16);
    index2->SetNProbe(16);

    size_t different_count = 0;
    for (size_t q = 0; q < 50; ++q) {
        auto r1 = index1->Search(data.queries.data() + q * D, TestUtils::KNN);
        auto r2 = index2->Search(data.queries.data() + q * D, TestUtils::KNN);
        if (r1.size() == r2.size()) {
            for (size_t i = 0; i < r1.size(); ++i) {
                if (r1[i].index != r2[i].index) {
                    ++different_count;
                    break;
                }
            }
        }
    }
    EXPECT_GT(different_count, 0u)
        << "Different seeds produced identical results for all 50 queries";
}

INSTANTIATE_TEST_SUITE_P(
    SeedDeterminism,
    SeedTest,
    ::testing::Values("pdx_f32", "pdx_u8"),
    [](const ::testing::TestParamInfo<std::string>& info) { return info.param; }
);

// --- Sampling Fraction Test ---

TEST(SamplingFractionTest, SamplingFractionDoesNotBreakSearch) {
    auto data = TestUtils::LoadTestData(D);
    auto gt = TestUtils::ComputeBruteForceKNN(
        data.train.data(),
        data.queries.data(),
        TestUtils::N_TRAIN,
        TestUtils::N_QUERIES,
        D,
        TestUtils::KNN
    );

    PDX::PDXIndexConfig full_config{
        .num_dimensions = static_cast<uint32_t>(D),
        .distance_metric = PDX::DistanceMetric::L2SQ,
        .seed = TestUtils::SEED,
        .normalize = true,
        .sampling_fraction = 1.0f,
        .hierarchical_indexing = true,
    };
    PDX::PDXIndexConfig sampled_config{
        .num_dimensions = static_cast<uint32_t>(D),
        .distance_metric = PDX::DistanceMetric::L2SQ,
        .seed = TestUtils::SEED,
        .normalize = true,
        .sampling_fraction = 0.3f,
        .hierarchical_indexing = true,
    };

    auto full_index = TestUtils::BuildIndexWithConfig(
        "pdx_f32", full_config, data.train.data(), TestUtils::N_TRAIN
    );
    auto sampled_index = TestUtils::BuildIndexWithConfig(
        "pdx_f32", sampled_config, data.train.data(), TestUtils::N_TRAIN
    );
    full_index->SetNProbe(0);
    sampled_index->SetNProbe(0);

    float full_recall = TestUtils::ComputeAverageRecall(
        *full_index, data.queries.data(), TestUtils::N_QUERIES, D, TestUtils::KNN, gt
    );
    float sampled_recall = TestUtils::ComputeAverageRecall(
        *sampled_index, data.queries.data(), TestUtils::N_QUERIES, D, TestUtils::KNN, gt
    );

    EXPECT_GE(full_recall, 0.90f) << "Full sampling exhaustive recall too low: " << full_recall;
    EXPECT_GE(sampled_recall, 0.90f)
        << "Sampled (0.3) exhaustive recall too low: " << sampled_recall;
}

} // namespace
